### ISSUE TITLE
Issue connecting to PostGIS store

### ISSUE THREAD

**Issue by mskyttner** [bioatlas/geoserver-docker#3]
![image](https://user-images.githubusercontent.com/1715840/46143020-0b2a4e80-c259-11e8-9b3d-9bd2a8c295b7.png)

**Comment by mskyttner** [comment]
The name of the PostGIS server that geoserver is aware of is defined in https://github.com/bioatlas/geoserver-docker/blob/master/docker-compose.yml#L44

Using "postgis" instead of "localhost" could fix this issue.

**Comment by vasnick** [comment]
Yes,
Found it in pg_hba.conf, works fine but now I have to create the database. Will look at https://github.com/bioatlas/geoserver-docker/issues/4 to access the server using pgAdmin with putty.

**Comment by vasnick** [comment]
Getting another error message now when we have created the database, is the geoserver allowed to access the database?:

Error creating data store, check the parameters. Error message: Unable to obtain connection: Cannot create PoolableConnectionFactory (The connection attempt failed.)

**Comment by vasnick** [comment]
The geoserver log contains this message when trying to create at store and it looks like there exists a problem accessing the databse from the geoserver using the host postgres:



Caused by: java.lang.RuntimeException: Unable to obtain connection: Cannot create PoolableConnectionFactory (The connection attempt failed.)
        at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:2170)
        at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:1014)
        at org.geotools.data.store.ContentDataStore.getTypeNames(ContentDataStore.java:308)
        at org.vfny.geoserver.util.DataStoreUtils.getDataAccess(DataStoreUtils.java:97)
        at org.geoserver.catalog.ResourcePool.getDataStore(ResourcePool.java:650)
        ... 134 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (The connection attempt failed.)
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
        at org.geotools.data.jdbc.datasource.AbstractManageableDataSource.getConnection(AbstractManageableDataSource.java:48)
        at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:2155)
        ... 138 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
        at org.postgresql.Driver.makeConnection(Driver.java:450)
        at org.postgresql.Driver.connect(Driver.java:252)
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
        at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
        ... 142 more
**Caused by: java.net.UnknownHostException: postgres**
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.postgresql.core.PGStream.<init>(PGStream.java:68)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)

**Comment by mskyttner** [comment]
Try to use `postgis` as the hostname and see if that works better.

The name of the server/microservice running the geoserver component on the SDN is defined here: https://github.com/bioatlas/geoserver-docker/blob/master/docker-compose.yml#L45.

It can be overridden if necessary - but this is not recommended normally and may cause issues when running in a cluster (I think): https://docs.docker.com/compose/compose-file/#container_name
